# Generated by Django 5.0.1 on 2024-02-28 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_song_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='counter',
            field=models.PositiveIntegerField(),
        ),
    ]
