# Generated by Django 5.0.1 on 2024-02-28 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_song_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='counter',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
