# Generated by Django 5.0.1 on 2024-03-01 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_song_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.CharField(choices=[('pop', 'pop'), ('club', 'club'), ('шансон', 'шансон'), ('rap', 'rap'), ('rock', 'rock'), ('trance', 'trance'), ('dance', 'dance')], max_length=64),
        ),
    ]
