# Generated by Django 5.0.2 on 2024-03-04 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_song_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.CharField(choices=[('pop', 'pop'), ('club', 'club'), ('шансон', 'шансон'), ('rap', 'rap'), ('rock', 'rock'), ('trance', 'trance'), ('dance', 'dance'), ('relax', 'relax'), ('dubstep', 'dubstep'), ('house', 'house'), ('metal', 'metal'), ('classic', 'classic'), ('rnb', 'rnb'), ('electric', 'electric'), ('instrumental', 'instrumental'), ('jazz', 'jazz'), ('blues', 'blues'), ('acustic', 'acustic'), ('techno', 'techno'), ('drum-n-base', 'drum-n-base'), ('alternative', 'alternative'), ('ethnic', 'ethnic'), ('indi', 'indi'), ('reggi', 'reggi'), ('soundtrack', 'soundtrack'), ('k-pop', 'k-pop'), ('hardstyle', 'hardstyle'), ('swing', 'swing'), ('old funk', 'old funk'), ('ska', 'ska'), ('eurodance', 'eurodance'), ('darkwave', 'darkwave'), ('country', 'country'), ('nu disco', 'nu disco'), ('synthwave', 'synthwave'), ('edm', 'edm'), ('italo disco', 'italo disco'), ('breakbeat', 'breakbeat'), ('screamo', 'screamo'), ('vaporwave', 'vaporwave'), ('8-bit', '8-bit'), ('noise', 'noise'), ('acid', 'acid'), ('lo-fi', 'lo-fi'), ('trip-hop', 'trip-hop'), ('electropop', 'electropop'), ('reggaeton', 'reggaeton'), ('guitar gloom', 'guitar gloom'), ('romances', 'romances'), ('folk', 'folk')], max_length=64),
        ),
    ]
